name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '00 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install mercury-parser
      run: npm install @postlight/mercury-parser
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: build scraper
      run: |
        python3 -m venv venv
        venv/bin/pip install -r requirements.txt
        venv/bin/python generate.py > rautenperle.xml
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add rautenperle.xml
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
